name: npm-publish

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14' # Version from your package.json
          registry-url: 'https://registry.npmjs.org/' # Specify the npm registry

      - name: Install dependencies
        run: npm ci # Use ci for more reliable installs in CI

      - name: Run npm publish script (will fail if version exists)
        run: npm run npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Pass the token for npm authentication 